version: "3.3"
services:
  redis:
    image: redis:alpine
  api:
    ports:
      - "8000:8000"
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    depends_on:
      - redis
    env_file:
      - env-postgres.env
      - env-backend.env
  frontend:
    ports:
      - "3000:3000"
    image: "${DOCKER_IMAGE_FRONTEND}:${TAG-latest}"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - api

